version: "2"

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    command: npm run start

  test:
    build : .
    volumes: 
      - ./src:/app/src
      - ./dist:/app/dist
    command: npm run test

  dev:
    build: .
    volumes: 
      - ./:/app
    command: bash
    stdin_open: true
    tty: true
    ports:
      - "9229:9229"